# Base webtop image
ARG BASEIMAGE
FROM ${BASEIMAGE}

# For which architecture to build (amd64 or arm64)
ARG arch

ENV HOME="/config"
ENV TZ=Europe/Paris
ARG DEBIAN_FRONTEND=noninteractive

# Install Isabelle 2022 for Why3
RUN \
	isabelle="Isabelle2022" ; \
	case ${arch} in \
		arm64) isabelletgz=${isabelle}_linux_arm.tar.gz ;; \
		amd64) isabelletgz=${isabelle}_linux.tar.gz ;; \
		*) echo "Unsupported architecture ${arch}" ;; \
	esac ; \
	curl --remote-name "https://isabelle.in.tum.de/website-${isabelle}/dist/${isabelletgz}" ; \
	tar zxf ${isabelletgz} && rm ${isabelletgz} ; \
	mv ${isabelle} /usr/local/Isabelle ; \
	ln -s /usr/local/Isabelle/bin/isabelle /usr/local/bin/isabelle

RUN  \
	apt-get update ; \
	apt-get upgrade -y

RUN \
	apt-get install -y \
	make cmake ocaml menhir libnum-ocaml-dev libmenhir-ocaml-dev libzarith-ocaml-dev \
	libzip-ocaml-dev liblablgtk3-ocaml-dev liblablgtksourceview3-ocaml-dev \
	libocamlgraph-ocaml-dev libre-ocaml-dev libjs-of-ocaml-dev z3 cvc4 \
	opam \
	yaru-theme-icon \
	adwaita-icon-theme-full \
	coqide \
	mesa-utils \
	libgl1-mesa-dri \
	python3-pip \
	python3-all-venv

# 	cvc5="cvc5-1.0.9" ; \
RUN \
	cvc5="cvc5-1.3.0" ; \
	curl --remote-name "https://codeload.github.com/cvc5/cvc5/tar.gz/refs/tags/${cvc5}" ; \
	mv ${cvc5} ${cvc5}.tar.gz ; \
	tar zxf ${cvc5}.tar.gz && rm ${cvc5}.tar.gz ; \
	cd cvc5-${cvc5} ; \
	./configure.sh --auto-download ; \
	cd build ; \
	make ; \
	make install ; \
	cd ../.. ; \
	rm -r cvc5-${cvc5}

RUN \
	mkdir /opt/opam ; \
	opam init --disable-sandboxing --root=/opt/opam --yes ; \
	eval $(opam env --root=/opt/opam) ; \
	export OPAMROOT=/opt/opam ; \
	opam install -y alt-ergo.2.6.0

RUN \
	why="why3-1.8.1" ; \
	whyisabelle="Isabelle2022" ; \
	curl -O https://why3.gitlabpages.inria.fr/releases/${why}.tar.gz ; \
	tar zxf ${why}.tar.gz && rm ${why}.tar.gz ; \
	cd ${why} ; \
	./configure ; \
	make ; \
	echo "/usr/local/lib/why3/isabelle" >> /usr/local/Isabelle/etc/components ; \
	make install ; \
	make byte ; \
	make install-lib ; \
	heapsdir=`ls -d /usr/local/Isabelle/heaps/polyml-*`; \
	homeheaps=`ls -d ${HOME}/.isabelle/${whyisabelle}/heaps/polyml-*`; \
	mv ${homeheaps}/Why3 ${heapsdir}/ ; \
	mv ${homeheaps}/log/* ${heapsdir}/log/ ; \
	cd .. ; \
	rm -r ${why}


RUN mkdir -p /init-config/init

COPY init-config-isabelle/init/* /init-config/init

RUN \
	cd /init-config/init ; \
	for script in *.sh ; \
	do \
		chmod +x $script ; \
		./$script ; \
	done ; \
	cd .. ; rm -r init

# Clean up
RUN apt-get autoremove && apt-get autoclean && apt-get clean ; \
		rm -rf \
    /tmp/* \
    /config/* \
    /var/lib/apt/lists/* \
    /var/tmp/*

ENTRYPOINT ["/bin/bash", "/usr/local/lib/wrapper_script.sh"]
